### PR TITLE
Added packaging support and alternative input option

### PR DESCRIPTION
**Pull request by hacevedo**
This requests includes 2 changes:

- Support for packaging (as [discussed](https://github.com/MRIMotionCorrection/parse_vNav_Motion/issues/7) previously) - would be available for install with following command: pip install git+https://github.com/MRIMotionCorrection/parse_vNav_Motion#egg=vnav

- Support for using previously extracted motion strings (i.e. in a BIDS JSON sidecar) as an alternative input option

### CODE REVIEW

**Comment by hacevedo** [comment]
The alternative input change is motivated by my use case which is to incorporate this into a BIDS app where the DICOM data is no longer accessible. The implementation included in this commit seems non-ideal since it relies on a hard-coded field ("vnavNumbers") in the JSON file, but (1) the field will hopefully be accepted into the BIDS standard so it'll make more sense to look for it, and (2) it was easier to implement than trying to deal with multiple data types for "input".

**Comment by mdtisdall** [comment]
Hi @hacevedo, apologies for not getting to this review faster. I see you're still adding features, which is great. Do you want me to hold off until you get to a stable place, or do you want me to look over all of the changes you have right now as one update?

**Comment by hacevedo** [comment]
No worries. Apologies for spamming your inbox as I keep changing my mind on how best to structure things. I think that it's currently in a good place if you want to go ahead and review it.

**Comment by hacevedo** [comment]
Sorry, last one. I tried to clean up what I thought was unnecessary code before asking you to review, but I accidentally removed python3 compatibility in the process. I've reverted the commit and will stop fiddling with it.

**Comment by mdtisdall** [comment]
Hi @hacevedo, I've finally got a chance to test this out thoroughly, and I have just one very small request: can you please add numpy as a dependency in setup.py? Otherwise, this all looks great and I really appreciate the work you did putting this together. Happy to accept the PR once that small change is in place!

**Comment by hacevedo** [comment]
Done! Thanks for reviewing it!

**Review by mdtisdall — APPROVED** [review]
All looks good!

**Comment by mharms** [comment]
Did this PR actually add 
`Support for using previously extracted motion strings (i.e. in a BIDS JSON sidecar) as an alternative input option` ?
I'm not seeing that as an option...

**Comment by hacevedo** [comment]
One of the early commits did have it as an input option, but ultimately I
refactored the parseMotion function to take in a list of motion numbers --
that way when importing it as a package, it can be used without having to
supply the DICOM files.

**Comment by mharms** [comment]
Do you have an example usage?  e.g., If you have the literal `ImageComments` already extracted in a json, how would you proceed?

**Comment by hacevedo** [comment]
https://github.com/BlackHershey/utils/blob/83ea4ba5943a11f88a00af25ef505c010abaabcb/bids/vnav2bids_v2.py#L32

It's redundant as it repeats the set up of readRotAndTrans. It would
probably benefit from further refactoring so that parseMotion could take in
the list of raw image comments and then do the transformation.

**Pull request merged**
